fun_fact_lib/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('fun_facts.urls')),

]

fun_facts/urls.py
"""Defines URL patterns for fun_facts."""

from django.urls import path

from . import views

app_name = 'fun_facts'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

fun_facts/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A topic the user is listing the fun fact under."""
    text = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True) 
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Something specific about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.text[:75]} etc"

users/models.py
from django.db import models

# Create your models here.

fun_facts/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

fun_facts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """The home page for the Fun Fact Library."""
    return render(request, 'fun_facts/index.html')

@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'fun_facts/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = get_object_or_404(Topic, id=topic_id)
    # Make sure the topic belongs to the current user.
    check_topic_owner(topic, request)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'fun_facts/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('fun_facts:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'fun_facts/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('fun_facts:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'fun_facts/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(topic, request)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('fun_facts:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'fun_facts/edit_entry.html', context)

def check_topic_owner(topic, request):
    """Check user associated with topic matches logged in user"""
    if topic.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.   
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('fun_facts:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

fun_facts/templates/fun_facts/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1,
         shrink-to-fit=no">
      <title>Fun Fact Library</title>
      {% bootstrap_css %}
      {% bootstrap_javascript jquery='full' %}
   </head>
   <body>
      <nav class="navbar navbar-dark bg-dark">
         <a class="navbar-brand" href="{% url 'fun_facts:index'%}">
         Fun Fact Library</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span></button>
         <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'fun_facts:topics'%}">
                  Topics</a>
               </li>
            </ul>
            <ul class="navbar-nav ml-auto">
               {% if user.is_authenticated %}
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
               </li>
               {% else %}
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:register' %}">Register</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
               </li>
               {% endif %}
            </ul>
         </div>
      </nav>
      <main role="main" class="container-fluid p-0 m-0 border-0">
         <div class="p-0 m-0 border-0"></div>
         {% block page_header %}{% endblock page_header %}
         <div>
            {% block content %}{% endblock content %}
         </div>
      </main>
   </body>
</html>

fun_facts/templates/fun_facts/edit_entry.html
{% extends "fun_facts/base.html" %}
{% block content %}
<h2 class= "p-5"><a href="{% url 'fun_facts:topic' topic.id %}">{{ topic }}</a></h2>
<p class= "px-5">Edit entry:</p>
<form class= "px-5" action="{% url 'fun_facts:edit_entry' entry.id %}" method='post'>
   {% csrf_token %}
   {{ form.as_p }}
   <button class="btn btn-secondary" name="submit">Save changes</button>
</form>
{% endblock content %}

fun_facts/templates/fun_facts/index.html
{% extends "fun_facts/base.html" %}
{% block page_header %}
<div class="jumbotron jumbotron-fluid vh-100 bg-dark text-light">
   <br>
   <br>
   <h1 class="display-2 text-center ">We heard you like<br>
      <strong>fun facts </strong> ;)
   </h1>
   <div class=" row d-flex justify-content-center align-content-center px-3 mx-3">
      <p class="lead text-center">Did you know....<br> you can create your own library of fun facts by listing topics
         and entries?
      </p>
   </div>
   <div class=" row d-flex justify-content-center align-content-center ">
      <a class="btn btn-outline-secondary" href="{% url 'users:register' %}"
         role="button">Register &raquo;</a>
   </div>
</div>
{% endblock page_header %}

fun_facts/templates/fun_facts/new_entry.html
{% extends "fun_facts/base.html" %}
{% block content %}
<h2 class="p-5"><a href="{% url 'fun_facts:topic' topic.id %}">{{ topic }}</a></h2>
<p class="px-5">Add New Entry:</p>
<form class="px-5" action="{% url 'fun_facts:new_entry' topic.id %}" method='post'>
   {% csrf_token %}
   {{ form.as_p }}
   <button class="btn btn-secondary" name='submit'>Add entry</button>
</form>
{% endblock content %}

fun_facts/templates/fun_facts/new_topic.html
{% extends "fun_facts/base.html" %}
{% block content %}
<div class=" row d-flex justify-content-center align-content-center p-5 m-5">
   <p>So your interested in adding a new topic to your library?</p>
</div>
<div class=" row d-flex justify-content-center align-content-center ">
   <form  action="{% url 'fun_facts:new_topic' %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <div class=" row d-flex justify-content-center align-content-center ">
         <button class="btn btn-secondary" name="submit">Add topic</button>
      </div>
   </form>
</div>
{% endblock content %}

fun_facts/templates/fun_facts/topic.html
{% extends 'fun_facts/base.html' %}
{% block page_header %}
<h2 class= "p-5">{{ topic }}</h2>
{% endblock page_header %}
{% block content %}
<p class= "px-5">
   <a href="{% url 'fun_facts:new_entry' topic.id %}">New Entry</a>
</p>
<ul>
{% for entry in entries %}
<div class="card mb-3">
   <h4 class="card-header">
      {{ entry.date_added|date:'M d, Y H:i' }}
      <br>
      <small><a href="{% url 'fun_facts:edit_entry' entry.id %}">
      Edit Entry</a></small>
   </h4>
   <div class="card-body">
      {{ entry.text|linebreaks }}
   </div>
</div>
{% empty %}
<p>There are no entries for this topic yet.</p>
{% endfor %}
{% endblock content %}

fun_facts/templates/fun_facts/topics.html
{% extends "fun_facts/base.html" %}
{% block page_header %}
<h1 class="text-center p-4">Topics</h1>
{% endblock page_header %}
{% block content %}
<br>
<div class="list-group list-group-item row">
   <div class="col-md-3 mx-auto">
      <ul>
         {% for topic in topics %}
         <li>
            <h3>
               <a href="{% url 'fun_facts:topic' topic.id %}">{{ topic }}</a>
            </h3>
         </li>
         {% empty %}
         <li>
            <h3>No topics have been added yet.</h3>
         </li>
         {% endfor %}
      </ul>
   </div>
</div>
<br>
<div class=" row d-flex justify-content-center align-content-center ">
   <a class="btn btn-secondary" href="{% url 'fun_facts:new_topic' %}"
      role="button">New Topic &raquo;</a>
</div>
{% endblock content %}